"""EchoTales core: models, store, and the ``state_of`` query.

This package imports nothing from the pipeline, by design. "Generation
pipelines do not need to understand the novel" is a claim the paper makes, and
`tools/check_deps.py` enforces it in CI so the claim stays true in code.
"""

from echotales.core.enums import (
    OBSERVER_READER,
    OBSERVER_SYSTEM,
    AliasType,
    AssertedBy,
    AttributionMethod,
    BlockType,
    Canonicity,
    Decision,
    EventType,
    NarrativeLayer,
    Prominence,
    Provenance,
    ReferenceMode,
    ResolutionMethod,
    SegmentType,
    SpanType,
    TargetKind,
    TruthStatus,
)
from echotales.core.interval import Certainty, FuzzyInterval, StoryPos
from echotales.core.models import (
    MAIN_TIMELINE,
    AliasBinding,
    Attribute,
    Block,
    Candidate,
    Chapter,
    DiscoursePosition,
    EvidenceVector,
    Mention,
    NarrativeSegment,
    Persona,
    Relation,
    ResolutionEvent,
    ResolutionOutcome,
    Self,
    SelfPersonaBinding,
    Span,
    StateOfResult,
)
from echotales.core.readset import CacheTier, ReadSetRecorder, hash_read_set
from echotales.core.state import StateResolver, state_of
from echotales.core.store import Store, normalize_alias

__all__ = [
    "MAIN_TIMELINE",
    "OBSERVER_READER",
    "OBSERVER_SYSTEM",
    "AliasBinding",
    "AliasType",
    "AssertedBy",
    "Attribute",
    "AttributionMethod",
    "Block",
    "BlockType",
    "CacheTier",
    "Candidate",
    "Canonicity",
    "Certainty",
    "Chapter",
    "Decision",
    "DiscoursePosition",
    "EventType",
    "EvidenceVector",
    "FuzzyInterval",
    "Mention",
    "NarrativeLayer",
    "NarrativeSegment",
    "Persona",
    "Prominence",
    "Provenance",
    "ReadSetRecorder",
    "ReferenceMode",
    "Relation",
    "ResolutionEvent",
    "ResolutionMethod",
    "ResolutionOutcome",
    "SegmentType",
    "Self",
    "SelfPersonaBinding",
    "Span",
    "SpanType",
    "StateOfResult",
    "StateResolver",
    "Store",
    "StoryPos",
    "TargetKind",
    "TruthStatus",
    "hash_read_set",
    "normalize_alias",
    "state_of",
]
